# encoding=UTF-8
"""
Django settings for gsinfosite project.

Generated by 'django-admin startproject' using Django 1.8.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import whoosh

reload(sys)
sys.setdefaultencoding('utf-8')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_PATH = os.path.join(BASE_DIR, 'templates')
STATIC_PATH = os.path.join(BASE_DIR, 'static')
DATA_PATH = os.path.join(BASE_DIR, 'data')
TAG_DATA_PATH = os.path.join(DATA_PATH, 'tag')
BOX_DATA_PATH = os.path.join(DATA_PATH, 'box')
WORK_DATA_PATH = os.path.join(DATA_PATH, 'work')
TEMPLATE_DATA_PATH = os.path.join(DATA_PATH, 'template')
PHOTO_DATA_PATH = os.path.join(DATA_PATH, 'photo')
HARDDIR = r''
# Printing paths for sanity's sake
# print 'Project root:', BASE_DIR
# print 'Templates:', TEMPLATE_PATH
# print 'Static:', STATIC_PATH
# print 'Tag Data:', TAG_DATA_PATH
# print 'Box Data:', BOX_DATA_PATH
# print 'Work Data:', WORK_DATA_PATH
# print 'Template Data:', TEMPLATE_DATA_PATH

# take pymysql as MySQLdb
import pymysql

pymysql.install_as_MySQLdb()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e4j1-4kr%g8m_2+!b(djj%2+86n0d_9nyev$fc7oc=%_n2%qj-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # haystack first then your own app
    'haystack',
    'gsinfo',
    'corsheaders',

)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'gsinfosite.urls'

# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#     '*'
# )
#
# CORS_ALLOW_METHODS = (
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
#     'VIEW',
# )
#
# CORS_ALLOW_HEADERS = (
#     'XMLHttpRequest',
#     'X_FILENAME',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     'Pragma',
# )

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gsinfosite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    # 'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gsinfo',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root',
        'PORT': '3306',
    },
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'gsinfo.whoosh_cn_backend.WhooshEngine',  # whoosh_backend 英文，whoosh_cn_backend 中文
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
# 设置搜索结果每页新显示数量
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
# 自动更新索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/gsinfo/login/'

# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    STATIC_PATH,
    BOX_DATA_PATH,
)
APPEND_SLASH=False
# DOWNLOAD_PATH
DATA_DIRS = {
    'tag_dir': TAG_DATA_PATH,
    'box_dir': BOX_DATA_PATH,
    'work_dir': WORK_DATA_PATH,
    'template_dir': TEMPLATE_DATA_PATH,
    'photo_dir': PHOTO_DATA_PATH,
}
