# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1259, 700)
        Form.setMaximumSize(QtCore.QSize(1267, 700))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(80, 30, 1101, 121))
        self.graphicsView.setStyleSheet("background-image:url(:/images/logo.jpg)")
        self.graphicsView.setObjectName("graphicsView")
        self.logoutButton = QtWidgets.QPushButton(Form)
        self.logoutButton.setGeometry(QtCore.QRect(1080, 70, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.logoutButton.setFont(font)
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon1)
        self.logoutButton.setIconSize(QtCore.QSize(25, 25))
        self.logoutButton.setObjectName("logoutButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(550, 110, 371, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.uploadButton = QtWidgets.QPushButton(Form)
        self.uploadButton.setGeometry(QtCore.QRect(950, 170, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uploadButton.setFont(font)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.uploadButton.setObjectName("uploadButton")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(80, 230, 1102, 403))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1083, 402))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1082, 402))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img1.setText("")
        self.img1.setScaledContents(True)
        self.img1.setObjectName("img1")
        self.horizontalLayout.addWidget(self.img1)
        self.img2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img2.setText("")
        self.img2.setScaledContents(True)
        self.img2.setObjectName("img2")
        self.horizontalLayout.addWidget(self.img2)
        self.img3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img3.setText("")
        self.img3.setScaledContents(True)
        self.img3.setObjectName("img3")
        self.horizontalLayout.addWidget(self.img3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 340, 1081, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.name1.setText("")
        self.name1.setAlignment(QtCore.Qt.AlignCenter)
        self.name1.setObjectName("name1")
        self.horizontalLayout_3.addWidget(self.name1)
        self.name2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.name2.setText("")
        self.name2.setAlignment(QtCore.Qt.AlignCenter)
        self.name2.setObjectName("name2")
        self.horizontalLayout_3.addWidget(self.name2)
        self.name3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.name3.setText("")
        self.name3.setScaledContents(False)
        self.name3.setAlignment(QtCore.Qt.AlignCenter)
        self.name3.setObjectName("name3")
        self.horizontalLayout_3.addWidget(self.name3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(2, 390, 1082, 341))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img4.setMinimumSize(QtCore.QSize(356, 339))
        self.img4.setText("")
        self.img4.setScaledContents(True)
        self.img4.setObjectName("img4")
        self.horizontalLayout_2.addWidget(self.img4)
        self.img5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img5.setMinimumSize(QtCore.QSize(356, 339))
        self.img5.setText("")
        self.img5.setScaledContents(True)
        self.img5.setObjectName("img5")
        self.horizontalLayout_2.addWidget(self.img5)
        self.img6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img6.setMinimumSize(QtCore.QSize(356, 309))
        self.img6.setText("")
        self.img6.setScaledContents(True)
        self.img6.setObjectName("img6")
        self.horizontalLayout_2.addWidget(self.img6)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 730, 1081, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.name4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.name4.setMaximumSize(QtCore.QSize(356, 49))
        self.name4.setText("")
        self.name4.setAlignment(QtCore.Qt.AlignCenter)
        self.name4.setObjectName("name4")
        self.horizontalLayout_4.addWidget(self.name4)
        self.name5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.name5.setMaximumSize(QtCore.QSize(356, 49))
        self.name5.setText("")
        self.name5.setAlignment(QtCore.Qt.AlignCenter)
        self.name5.setObjectName("name5")
        self.horizontalLayout_4.addWidget(self.name5)
        self.name6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.name6.setMaximumSize(QtCore.QSize(356, 49))
        self.name6.setText("")
        self.name6.setAlignment(QtCore.Qt.AlignCenter)
        self.name6.setObjectName("name6")
        self.horizontalLayout_4.addWidget(self.name6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 780, 1081, 341))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.img7.setMinimumSize(QtCore.QSize(356, 339))
        self.img7.setText("")
        self.img7.setScaledContents(True)
        self.img7.setObjectName("img7")
        self.horizontalLayout_5.addWidget(self.img7)
        self.img8 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.img8.setText("")
        self.img8.setScaledContents(True)
        self.img8.setObjectName("img8")
        self.horizontalLayout_5.addWidget(self.img8)
        self.img9 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.img9.setText("")
        self.img9.setScaledContents(True)
        self.img9.setObjectName("img9")
        self.horizontalLayout_5.addWidget(self.img9)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 1120, 1081, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.name7 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.name7.setMaximumSize(QtCore.QSize(356, 49))
        self.name7.setText("")
        self.name7.setAlignment(QtCore.Qt.AlignCenter)
        self.name7.setObjectName("name7")
        self.horizontalLayout_6.addWidget(self.name7)
        self.name8 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.name8.setMaximumSize(QtCore.QSize(355, 49))
        self.name8.setText("")
        self.name8.setAlignment(QtCore.Qt.AlignCenter)
        self.name8.setObjectName("name8")
        self.horizontalLayout_6.addWidget(self.name8)
        self.name9 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.name9.setMaximumSize(QtCore.QSize(356, 49))
        self.name9.setText("")
        self.name9.setAlignment(QtCore.Qt.AlignCenter)
        self.name9.setObjectName("name9")
        self.horizontalLayout_6.addWidget(self.name9)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 1170, 1081, 341))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.img10 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.img10.setText("")
        self.img10.setScaledContents(True)
        self.img10.setObjectName("img10")
        self.horizontalLayout_7.addWidget(self.img10)
        self.img11 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.img11.setText("")
        self.img11.setScaledContents(True)
        self.img11.setObjectName("img11")
        self.horizontalLayout_7.addWidget(self.img11)
        self.img12 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.img12.setMinimumSize(QtCore.QSize(356, 339))
        self.img12.setText("")
        self.img12.setScaledContents(True)
        self.img12.setObjectName("img12")
        self.horizontalLayout_7.addWidget(self.img12)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 1510, 1081, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.name10 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.name10.setText("")
        self.name10.setAlignment(QtCore.Qt.AlignCenter)
        self.name10.setObjectName("name10")
        self.horizontalLayout_8.addWidget(self.name10)
        self.name11 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.name11.setText("")
        self.name11.setAlignment(QtCore.Qt.AlignCenter)
        self.name11.setObjectName("name11")
        self.horizontalLayout_8.addWidget(self.name11)
        self.name12 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.name12.setText("")
        self.name12.setAlignment(QtCore.Qt.AlignCenter)
        self.name12.setObjectName("name12")
        self.horizontalLayout_8.addWidget(self.name12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.codeButton = QtWidgets.QPushButton(Form)
        self.codeButton.setGeometry(QtCore.QRect(810, 170, 90, 40))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.codeButton.setFont(font)
        self.codeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.codeButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.codeButton.setObjectName("codeButton")
        self.delButton = QtWidgets.QPushButton(Form)
        self.delButton.setGeometry(QtCore.QRect(1080, 170, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delButton.setFont(font)
        self.delButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.delButton.setObjectName("delButton")

        self.retranslateUi(Form)
        self.logoutButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图像采集岗"))
        self.logoutButton.setText(_translate("Form", "退出"))
        self.label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun-ExtB\'; font-size:25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffff99;\">金银清点查验业务系统</span></p></body></html>"))
        self.uploadButton.setText(_translate("Form", "上传"))
        self.codeButton.setText(_translate("Form", "扫描二维码"))
        self.delButton.setText(_translate("Form", "删除"))

import image_path_rc
