# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsthing',
            name='subBox',
        ),
        migrations.AddField(
            model_name='gsthing',
            name='subBoxNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
